version: 1.0.{build}-{branch}
image: Visual Studio 2017
configuration: Release
before_build:
  - nuget restore
build:
  project: sfdx4csharp.sln
  verbosity: minimal
  publish_nuget: true
branches:
  only:
    - master
deploy:
  provider: NuGet
  api_key:
    secure: xsNG1BjaS8hjq5uuT527akgjGakOUiOsjCWVMqI9wDn10GzHXe1l/U5czJHchhbi  # encrypted token from Nuget
  on:
    branch: test-deploy
    APPVEYOR_REPO_TAG: true
